export type DemoAccount = {
  name: string;
  domain: string;
  city: string;
  street: string;
  employees: number;
  annualRevenue: number;
  businessSegment: string;
  ownershipType: string;
  salesRegion: string;
  accountManager: string;
};

export type DemoContact = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  jobTitle: string;
  accountName: string;
};

export type DemoOpportunity = {
  name: string;
  accountName: string;
  contactEmail: string;
  stage: string;
  amount: number;
  closeDate: string;
  probabilityOfClosure: number;
  businessSegment: string;
  productService: string;
  accountManager: string;
  salesManager: string;
  competitor?: string;
  lossReason?: string;
};

export type DemoContract = {
  contractNumber: string;
  name: string;
  accountName: string;
  contactEmail: string;
  opportunityName: string;
  accountManager: string;
  salesManager: string;
  contractType: string;
  description: string;
  value: number;
  effectiveDate: string;
  expiryDate: string;
  noticePeriodDays: number;
  renewalType: string;
  autoRenewal: boolean;
  billingFrequency: string;
  slaServiceTier: string;
  status: string;
};

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    name: 'Kafue Horizon Manufacturing',
    domain: 'kafue-horizon.example',
    city: 'Kafue',
    street: '18 Industrial Way',
    employees: 420,
    annualRevenue: 128000000,
    businessSegment: 'CORPORATE',
    ownershipType: 'PRIVATE',
    salesRegion: 'LUSAKA',
    accountManager: 'CHILESHE_MWILA',
  },
  {
    name: 'Copper Trail Logistics',
    domain: 'copper-trail.example',
    city: 'Ndola',
    street: '42 Freedom Park Road',
    employees: 260,
    annualRevenue: 76000000,
    businessSegment: 'CORPORATE',
    ownershipType: 'PRIVATE',
    salesRegion: 'COPPERBELT',
    accountManager: 'BUPE_BANDA',
  },
  {
    name: 'Mukwa Agro Processing',
    domain: 'mukwa-agro.example',
    city: 'Choma',
    street: '7 Market Link',
    employees: 185,
    annualRevenue: 54000000,
    businessSegment: 'SME',
    ownershipType: 'PRIVATE',
    salesRegion: 'SOUTHERN',
    accountManager: 'THANDIWE_ZULU',
  },
  {
    name: 'Northern Star Mining Services',
    domain: 'northern-star.example',
    city: 'Solwezi',
    street: '11 Kansanshi Crescent',
    employees: 610,
    annualRevenue: 215000000,
    businessSegment: 'CORPORATE',
    ownershipType: 'PRIVATE',
    salesRegion: 'NORTHERN',
    accountManager: 'MUTINTA_PHIRI',
  },
  {
    name: 'Lusaka Civic Technologies',
    domain: 'lusaka-civic.example',
    city: 'Lusaka',
    street: '25 Independence Avenue',
    employees: 310,
    annualRevenue: 98000000,
    businessSegment: 'GOVERNMENT',
    ownershipType: 'PUBLIC',
    salesRegion: 'LUSAKA',
    accountManager: 'CHILESHE_MWILA',
  },
  {
    name: 'Zambezi Fresh Foods',
    domain: 'zambezi-fresh.example',
    city: 'Livingstone',
    street: '9 Mosi-oa-Tunya Road',
    employees: 145,
    annualRevenue: 44000000,
    businessSegment: 'SME',
    ownershipType: 'PRIVATE',
    salesRegion: 'SOUTHERN',
    accountManager: 'THANDIWE_ZULU',
  },
  {
    name: 'Meridian Health Supplies',
    domain: 'meridian-health.example',
    city: 'Lusaka',
    street: '33 Kabulonga Road',
    employees: 220,
    annualRevenue: 68000000,
    businessSegment: 'CORPORATE',
    ownershipType: 'PRIVATE',
    salesRegion: 'LUSAKA',
    accountManager: 'MUTINTA_PHIRI',
  },
  {
    name: 'Luangwa Education Network',
    domain: 'luangwa-education.example',
    city: 'Chipata',
    street: '14 Great East Road',
    employees: 520,
    annualRevenue: 87000000,
    businessSegment: 'GOVERNMENT',
    ownershipType: 'PUBLIC',
    salesRegion: 'OTHER',
    accountManager: 'CHILESHE_MWILA',
  },
  {
    name: 'Copperbelt Precision Works',
    domain: 'copperbelt-precision.example',
    city: 'Kitwe',
    street: '5 Foundry Close',
    employees: 95,
    annualRevenue: 31000000,
    businessSegment: 'SME',
    ownershipType: 'PRIVATE',
    salesRegion: 'COPPERBELT',
    accountManager: 'BUPE_BANDA',
  },
  {
    name: 'Muchinga Renewable Energy',
    domain: 'muchinga-renewable.example',
    city: 'Chinsali',
    street: '20 Central Plateau Road',
    employees: 170,
    annualRevenue: 59000000,
    businessSegment: 'CORPORATE',
    ownershipType: 'PRIVATE',
    salesRegion: 'NORTHERN',
    accountManager: 'MUTINTA_PHIRI',
  },
  {
    name: 'Capital Retail Cooperative',
    domain: 'capital-retail.example',
    city: 'Lusaka',
    street: '61 Cairo Road',
    employees: 380,
    annualRevenue: 112000000,
    businessSegment: 'OTHER',
    ownershipType: 'PUBLIC',
    salesRegion: 'LUSAKA',
    accountManager: 'CHILESHE_MWILA',
  },
  {
    name: 'Southern Cross Hospitality',
    domain: 'southern-cross.example',
    city: 'Livingstone',
    street: '3 Riverside Drive',
    employees: 240,
    annualRevenue: 72000000,
    businessSegment: 'CORPORATE',
    ownershipType: 'PRIVATE',
    salesRegion: 'SOUTHERN',
    accountManager: 'THANDIWE_ZULU',
  },
];

export const DEMO_CONTACTS: DemoContact[] = [
  {
    firstName: 'Luyando',
    lastName: 'Tembo',
    email: 'luyando.tembo@kafue-horizon.example',
    phone: '971000101',
    jobTitle: 'ICT Director',
    accountName: 'Kafue Horizon Manufacturing',
  },
  {
    firstName: 'Mwamba',
    lastName: 'Chola',
    email: 'mwamba.chola@kafue-horizon.example',
    phone: '971000102',
    jobTitle: 'Finance Manager',
    accountName: 'Kafue Horizon Manufacturing',
  },
  {
    firstName: 'Natasha',
    lastName: 'Musonda',
    email: 'natasha.musonda@copper-trail.example',
    phone: '971000103',
    jobTitle: 'Head of Operations',
    accountName: 'Copper Trail Logistics',
  },
  {
    firstName: 'Kondwani',
    lastName: 'Lungu',
    email: 'kondwani.lungu@mukwa-agro.example',
    phone: '971000104',
    jobTitle: 'Managing Director',
    accountName: 'Mukwa Agro Processing',
  },
  {
    firstName: 'Chanda',
    lastName: 'Mulenga',
    email: 'chanda.mulenga@northern-star.example',
    phone: '971000105',
    jobTitle: 'Chief Information Officer',
    accountName: 'Northern Star Mining Services',
  },
  {
    firstName: 'Mapalo',
    lastName: 'Sichone',
    email: 'mapalo.sichone@northern-star.example',
    phone: '971000106',
    jobTitle: 'Procurement Manager',
    accountName: 'Northern Star Mining Services',
  },
  {
    firstName: 'Musonda',
    lastName: 'Hamaimbo',
    email: 'musonda.hamaimbo@lusaka-civic.example',
    phone: '971000107',
    jobTitle: 'Director of Technology',
    accountName: 'Lusaka Civic Technologies',
  },
  {
    firstName: 'Thandi',
    lastName: 'Mweemba',
    email: 'thandi.mweemba@zambezi-fresh.example',
    phone: '971000108',
    jobTitle: 'Operations Director',
    accountName: 'Zambezi Fresh Foods',
  },
  {
    firstName: 'Mwila',
    lastName: 'Soko',
    email: 'mwila.soko@meridian-health.example',
    phone: '971000109',
    jobTitle: 'Infrastructure Manager',
    accountName: 'Meridian Health Supplies',
  },
  {
    firstName: 'Lombe',
    lastName: 'Zulu',
    email: 'lombe.zulu@meridian-health.example',
    phone: '971000110',
    jobTitle: 'Commercial Director',
    accountName: 'Meridian Health Supplies',
  },
  {
    firstName: 'Chisomo',
    lastName: 'Njobvu',
    email: 'chisomo.njobvu@luangwa-education.example',
    phone: '971000111',
    jobTitle: 'ICT Coordinator',
    accountName: 'Luangwa Education Network',
  },
  {
    firstName: 'Bupe',
    lastName: 'Mumba',
    email: 'bupe.mumba@copperbelt-precision.example',
    phone: '971000112',
    jobTitle: 'General Manager',
    accountName: 'Copperbelt Precision Works',
  },
  {
    firstName: 'Mwewa',
    lastName: 'Kabwe',
    email: 'mwewa.kabwe@muchinga-renewable.example',
    phone: '971000113',
    jobTitle: 'Programme Director',
    accountName: 'Muchinga Renewable Energy',
  },
  {
    firstName: 'Tamara',
    lastName: 'Phiri',
    email: 'tamara.phiri@capital-retail.example',
    phone: '971000114',
    jobTitle: 'Chief Executive Officer',
    accountName: 'Capital Retail Cooperative',
  },
  {
    firstName: 'Bwalya',
    lastName: 'Nyirenda',
    email: 'bwalya.nyirenda@southern-cross.example',
    phone: '971000115',
    jobTitle: 'Group IT Manager',
    accountName: 'Southern Cross Hospitality',
  },
  {
    firstName: 'Mutale',
    lastName: 'Siame',
    email: 'mutale.siame@southern-cross.example',
    phone: '971000116',
    jobTitle: 'Finance Director',
    accountName: 'Southern Cross Hospitality',
  },
];

export const DEMO_OPPORTUNITIES: DemoOpportunity[] = [
  {
    name: 'Kafue plant resilient connectivity',
    accountName: 'Kafue Horizon Manufacturing',
    contactEmail: 'luyando.tembo@kafue-horizon.example',
    stage: 'PROSPECTING',
    amount: 1850000,
    closeDate: '2027-02-26',
    probabilityOfClosure: 15,
    businessSegment: 'CORPORATE',
    productService: 'DEDICATED_INTERNET',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Copper Trail national SD-WAN',
    accountName: 'Copper Trail Logistics',
    contactEmail: 'natasha.musonda@copper-trail.example',
    stage: 'QUALIFICATION',
    amount: 4200000,
    closeDate: '2027-03-19',
    probabilityOfClosure: 25,
    businessSegment: 'CORPORATE',
    productService: 'MPLS_SDWAN',
    accountManager: 'BUPE_BANDA',
    salesManager: 'NATASHA_MBEWE',
    competitor: 'Regional network provider',
  },
  {
    name: 'Mukwa managed branch network',
    accountName: 'Mukwa Agro Processing',
    contactEmail: 'kondwani.lungu@mukwa-agro.example',
    stage: 'SOLUTION_DEVELOPMENT',
    amount: 980000,
    closeDate: '2027-01-29',
    probabilityOfClosure: 40,
    businessSegment: 'SME',
    productService: 'MANAGED_ICT',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
  },
  {
    name: 'Northern Star private cloud',
    accountName: 'Northern Star Mining Services',
    contactEmail: 'chanda.mulenga@northern-star.example',
    stage: 'PROPOSAL_COMMERCIALS',
    amount: 7800000,
    closeDate: '2027-04-30',
    probabilityOfClosure: 55,
    businessSegment: 'CORPORATE',
    productService: 'CLOUD_DATA_CENTRE',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
    competitor: 'Pan-African cloud operator',
  },
  {
    name: 'Civic offices unified communications',
    accountName: 'Lusaka Civic Technologies',
    contactEmail: 'musonda.hamaimbo@lusaka-civic.example',
    stage: 'NEGOTIATION',
    amount: 3600000,
    closeDate: '2026-12-18',
    probabilityOfClosure: 70,
    businessSegment: 'GOVERNMENT',
    productService: 'UNIFIED_COMMUNICATIONS',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Zambezi Fresh mobile workforce',
    accountName: 'Zambezi Fresh Foods',
    contactEmail: 'thandi.mweemba@zambezi-fresh.example',
    stage: 'COMMITMENT',
    amount: 640000,
    closeDate: '2026-11-27',
    probabilityOfClosure: 85,
    businessSegment: 'SME',
    productService: 'MOBILE_ENTERPRISE',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
  },
  {
    name: 'Meridian secure data centre',
    accountName: 'Meridian Health Supplies',
    contactEmail: 'mwila.soko@meridian-health.example',
    stage: 'CLOSURE',
    amount: 2950000,
    closeDate: '2026-11-13',
    probabilityOfClosure: 95,
    businessSegment: 'CORPORATE',
    productService: 'CLOUD_DATA_CENTRE',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Luangwa schools bandwidth uplift',
    accountName: 'Luangwa Education Network',
    contactEmail: 'chisomo.njobvu@luangwa-education.example',
    stage: 'ACCOUNT_GROWTH',
    amount: 5100000,
    closeDate: '2027-01-15',
    probabilityOfClosure: 90,
    businessSegment: 'GOVERNMENT',
    productService: 'DEDICATED_INTERNET',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Precision Works fibre access',
    accountName: 'Copperbelt Precision Works',
    contactEmail: 'bupe.mumba@copperbelt-precision.example',
    stage: 'PROSPECTING',
    amount: 420000,
    closeDate: '2027-05-28',
    probabilityOfClosure: 10,
    businessSegment: 'SME',
    productService: 'DEDICATED_INTERNET',
    accountManager: 'BUPE_BANDA',
    salesManager: 'NATASHA_MBEWE',
  },
  {
    name: 'Muchinga field connectivity',
    accountName: 'Muchinga Renewable Energy',
    contactEmail: 'mwewa.kabwe@muchinga-renewable.example',
    stage: 'QUALIFICATION',
    amount: 1700000,
    closeDate: '2027-04-16',
    probabilityOfClosure: 30,
    businessSegment: 'CORPORATE',
    productService: 'MOBILE_ENTERPRISE',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Capital Retail managed security',
    accountName: 'Capital Retail Cooperative',
    contactEmail: 'tamara.phiri@capital-retail.example',
    stage: 'SOLUTION_DEVELOPMENT',
    amount: 2400000,
    closeDate: '2027-03-12',
    probabilityOfClosure: 45,
    businessSegment: 'OTHER',
    productService: 'MANAGED_ICT',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Southern Cross guest connectivity',
    accountName: 'Southern Cross Hospitality',
    contactEmail: 'bwalya.nyirenda@southern-cross.example',
    stage: 'PROPOSAL_COMMERCIALS',
    amount: 1950000,
    closeDate: '2027-02-12',
    probabilityOfClosure: 60,
    businessSegment: 'CORPORATE',
    productService: 'DEDICATED_INTERNET',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
    competitor: 'Hospitality connectivity vendor',
  },
  {
    name: 'Copper Trail fleet mobility',
    accountName: 'Copper Trail Logistics',
    contactEmail: 'natasha.musonda@copper-trail.example',
    stage: 'NEGOTIATION',
    amount: 1250000,
    closeDate: '2026-12-11',
    probabilityOfClosure: 72,
    businessSegment: 'CORPORATE',
    productService: 'MOBILE_ENTERPRISE',
    accountManager: 'BUPE_BANDA',
    salesManager: 'NATASHA_MBEWE',
  },
  {
    name: 'Northern Star unified operations',
    accountName: 'Northern Star Mining Services',
    contactEmail: 'mapalo.sichone@northern-star.example',
    stage: 'COMMITMENT',
    amount: 3300000,
    closeDate: '2026-12-04',
    probabilityOfClosure: 82,
    businessSegment: 'CORPORATE',
    productService: 'UNIFIED_COMMUNICATIONS',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Meridian branch SD-WAN',
    accountName: 'Meridian Health Supplies',
    contactEmail: 'lombe.zulu@meridian-health.example',
    stage: 'CLOSURE',
    amount: 2180000,
    closeDate: '2026-11-20',
    probabilityOfClosure: 94,
    businessSegment: 'CORPORATE',
    productService: 'MPLS_SDWAN',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
  },
  {
    name: 'Southern Cross cloud backup expansion',
    accountName: 'Southern Cross Hospitality',
    contactEmail: 'mutale.siame@southern-cross.example',
    stage: 'ACCOUNT_GROWTH',
    amount: 860000,
    closeDate: '2027-01-22',
    probabilityOfClosure: 88,
    businessSegment: 'CORPORATE',
    productService: 'CLOUD_DATA_CENTRE',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
  },
];

export const DEMO_CONTRACTS: DemoContract[] = [
  {
    contractNumber: 'ZBC-CTR-000001',
    name: 'Kafue resilient dedicated internet agreement',
    accountName: 'Kafue Horizon Manufacturing',
    contactEmail: 'luyando.tembo@kafue-horizon.example',
    opportunityName: 'Kafue plant resilient connectivity',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
    contractType: 'CONNECTIVITY',
    description: 'Primary and failover dedicated internet for the Kafue plant.',
    value: 2880000,
    effectiveDate: '2025-05-01',
    expiryDate: '2027-04-30',
    noticePeriodDays: 60,
    renewalType: 'MANUAL',
    autoRenewal: false,
    billingFrequency: 'MONTHLY',
    slaServiceTier: 'PRIORITY',
    status: 'ACTIVE',
  },
  {
    contractNumber: 'ZBC-CTR-000002',
    name: 'Copper Trail national MPLS agreement',
    accountName: 'Copper Trail Logistics',
    contactEmail: 'natasha.musonda@copper-trail.example',
    opportunityName: 'Copper Trail national SD-WAN',
    accountManager: 'BUPE_BANDA',
    salesManager: 'NATASHA_MBEWE',
    contractType: 'CONNECTIVITY',
    description: 'Managed MPLS connectivity across national logistics depots.',
    value: 4560000,
    effectiveDate: '2025-01-06',
    expiryDate: '2027-01-05',
    noticePeriodDays: 60,
    renewalType: 'RENEGOTIATION',
    autoRenewal: false,
    billingFrequency: 'MONTHLY',
    slaServiceTier: 'MISSION_CRITICAL',
    status: 'ACTIVE',
  },
  {
    contractNumber: 'ZBC-CTR-000003',
    name: 'Mukwa managed connectivity service',
    accountName: 'Mukwa Agro Processing',
    contactEmail: 'kondwani.lungu@mukwa-agro.example',
    opportunityName: 'Mukwa managed branch network',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
    contractType: 'MANAGED_SERVICES',
    description:
      'Managed branch connectivity and proactive service monitoring.',
    value: 1260000,
    effectiveDate: '2025-12-01',
    expiryDate: '2026-12-01',
    noticePeriodDays: 30,
    renewalType: 'MANUAL',
    autoRenewal: false,
    billingFrequency: 'MONTHLY',
    slaServiceTier: 'STANDARD',
    status: 'ACTIVE',
  },
  {
    contractNumber: 'ZBC-CTR-000004',
    name: 'Northern Star cloud hosting agreement',
    accountName: 'Northern Star Mining Services',
    contactEmail: 'chanda.mulenga@northern-star.example',
    opportunityName: 'Northern Star private cloud',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
    contractType: 'MANAGED_SERVICES',
    description:
      'Private cloud hosting for mine operations and reporting workloads.',
    value: 6240000,
    effectiveDate: '2025-11-06',
    expiryDate: '2026-11-05',
    noticePeriodDays: 30,
    renewalType: 'RENEGOTIATION',
    autoRenewal: false,
    billingFrequency: 'MONTHLY',
    slaServiceTier: 'MISSION_CRITICAL',
    status: 'EXPIRING',
  },
  {
    contractNumber: 'ZBC-CTR-000005',
    name: 'Lusaka Civic enterprise mobile service',
    accountName: 'Lusaka Civic Technologies',
    contactEmail: 'musonda.hamaimbo@lusaka-civic.example',
    opportunityName: 'Civic offices unified communications',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
    contractType: 'SERVICE_AGREEMENT',
    description:
      'Enterprise mobile connectivity for civic technology field teams.',
    value: 980000,
    effectiveDate: '2025-10-21',
    expiryDate: '2026-10-20',
    noticePeriodDays: 30,
    renewalType: 'AUTO_RENEWAL',
    autoRenewal: true,
    billingFrequency: 'MONTHLY',
    slaServiceTier: 'PRIORITY',
    status: 'EXPIRING',
  },
  {
    contractNumber: 'ZBC-CTR-000006',
    name: 'Zambezi Fresh bulk SMS service',
    accountName: 'Zambezi Fresh Foods',
    contactEmail: 'thandi.mweemba@zambezi-fresh.example',
    opportunityName: 'Zambezi Fresh mobile workforce',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
    contractType: 'SERVICE_AGREEMENT',
    description:
      'Bulk SMS service for customer promotions and delivery alerts.',
    value: 540000,
    effectiveDate: '2025-10-13',
    expiryDate: '2026-10-12',
    noticePeriodDays: 14,
    renewalType: 'MANUAL',
    autoRenewal: false,
    billingFrequency: 'QUARTERLY',
    slaServiceTier: 'STANDARD',
    status: 'EXPIRING',
  },
  {
    contractNumber: 'ZBC-CTR-000007',
    name: 'Meridian health managed WAN renewal',
    accountName: 'Meridian Health Supplies',
    contactEmail: 'mwila.soko@meridian-health.example',
    opportunityName: 'Meridian secure data centre',
    accountManager: 'MUTINTA_PHIRI',
    salesManager: 'MWAPE_SAKALA',
    contractType: 'MANAGED_SERVICES',
    description:
      'Renewal workstream for managed WAN across health supply branches.',
    value: 3120000,
    effectiveDate: '2025-11-30',
    expiryDate: '2026-11-30',
    noticePeriodDays: 30,
    renewalType: 'RENEGOTIATION',
    autoRenewal: false,
    billingFrequency: 'MONTHLY',
    slaServiceTier: 'PRIORITY',
    status: 'RENEWAL_IN_PROGRESS',
  },
  {
    contractNumber: 'ZBC-CTR-000008',
    name: 'Luangwa education cloud hosting',
    accountName: 'Luangwa Education Network',
    contactEmail: 'chisomo.njobvu@luangwa-education.example',
    opportunityName: 'Luangwa schools bandwidth uplift',
    accountManager: 'CHILESHE_MWILA',
    salesManager: 'MWAPE_SAKALA',
    contractType: 'MANAGED_SERVICES',
    description: 'Cloud hosting for education network collaboration services.',
    value: 1440000,
    effectiveDate: '2025-10-01',
    expiryDate: '2026-10-02',
    noticePeriodDays: 30,
    renewalType: 'MANUAL',
    autoRenewal: false,
    billingFrequency: 'ANNUALLY',
    slaServiceTier: 'STANDARD',
    status: 'EXPIRED',
  },
  {
    contractNumber: 'ZBC-CTR-000009',
    name: 'Southern Cross IoT connectivity pilot',
    accountName: 'Southern Cross Hospitality',
    contactEmail: 'bwalya.nyirenda@southern-cross.example',
    opportunityName: 'Southern Cross cloud backup expansion',
    accountManager: 'THANDIWE_ZULU',
    salesManager: 'NATASHA_MBEWE',
    contractType: 'FRAMEWORK_AGREEMENT',
    description:
      'Closed IoT connectivity pilot for hospitality site monitoring.',
    value: 760000,
    effectiveDate: '2025-02-01',
    expiryDate: '2026-08-31',
    noticePeriodDays: 30,
    renewalType: 'MANUAL',
    autoRenewal: false,
    billingFrequency: 'ONE_TIME',
    slaServiceTier: 'STANDARD',
    status: 'TERMINATED',
  },
];
